### ISSUE TITLE
Review of README.md

### ISSUE THREAD

**Issue by binnes** [IBM/node-red-tensorflowjs#5]
- There are no dependencies given, though when reading through the instructions it is clear that a working Node.js installation with npm is needed and python 2.7.x is also needed (pity python 3 is not supported as python 2 has reached end of development and is rapidly approaching end of life - April 2020).
- Prerequisite knowledge - there is the assumption that the developer is already familiar with Node-RED (open Node-RED menu, use palette manager to install nodes, deploy...)
- Install Node-RED section : The Node-RED **editor** or **Web User Interface** can be accessed on http://localhost:1880 - dashboard is used to refer to the UI created by the dashboard nodes and is found on http://localhost:1880/ui
- confusing instructions - **Install Node-RED** ends with the command to start Node-RED then the next step, **Install the TensorFlow.js node** asks the developer to restart Node-RED without saying how, then **Import the Node-RED flow** starts with the instruction to "Start your Node-RED application"
- Clarity - **Run on a RaspberryP**i vs **Run from a browser**.  Isn't all Node-RED run from a browser?  Maybe it would be better if this said **Running on a Raspberry Pi** vs **Running on a laptop or workstation**.  The distinction is where the Node-RED server is running?

**Comment by vabarbosa** [comment]
thanks. README has been updated to try to clarify on the above comments. let me know if anything is missed or additional updates required.
